#2627 Build failing with: error TS1205: Re-exporting a type when 'isolatedModules' is enabled requires using 'export type'. (#2626)
Signed-off-by: Mariya George <mgkofficial001@gmail.com>